# .github/workflows/build.yml
# -------------------------------------------------
# CI workflow for a pnpm‑based project
# * Caches dependencies via actions/setup-node@v4
# * Uses Node 20 – adjust if you need another version
# * Runs “pnpm install --frozen-lockfile” then your build script
# -------------------------------------------------

name: build

on:
  push:
    branches: [main]        # run on every push to main
  pull_request:             # and on PRs targeting main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out repository
      - uses: actions/checkout@v4

      # 2. Install pnpm itself
      - uses: pnpm/action-setup@v2
        with:
          version: 9               # pick a pnpm version ≥ 6.10
          run_install: false       # we’ll run install explicitly later

      # 3. Set up Node and dependency cache
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm              # tells the action to use pnpm cache
          cache-dependency-path: pnpm-lock.yaml  # location of the lock file

      # 4. Install deps & build
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build        # replace with your actual build command
